### PR TITLE
Adds a --timeout option, for cases in which five seconds is not enough.

### PR DESCRIPTION
**Pull request by dbergey**

### CODE REVIEW

**Comment by dblandin** [comment]
Hey @dbergey,

Thank you for the PR, but 'm a bit hesitant to merge PRs on this repo now that our [new test reporter](https://github.com/codeclimate/test-reporter) ([changelog](https://codeclimate.com/changelog/591c99570d51f6481f001291)) is available.

It's decoupled from the coverage tool used to generate the report, distributed as a static binary, and has support for parallelized builds. 🎉

Another option would be to fork the project and point `package.json` to your fork:

```json
"dependencies" : {
   "javascript-test-reporter" : "dbergey/javascript-test-reporter"
}
```

**Comment by dbergey** [comment]
We are currently using our forked version, so that will work for the forseeable future.
Is the new test reporter still in "beta"?
Is the upload timeout configurable in the new tool?
Do you plan to release an NPM package for ease of installation?
Thanks

**Comment by dblandin** [comment]
> Is the new test reporter still in "beta"?

The new test reporter is in public beta right now, so there may be some changes to the interface before `v1.0`. We do publish versioned binaries which you can lock to instead of pulling `latest` if that's a concern.

> Is the upload timeout configurable in the new tool?

Not currently. Looks like it's set to 30 seconds right now:
https://github.com/codeclimate/test-reporter/blob/420ceb13768d27f64df2cc94d958713608dc98df/upload/uploader.go#L124

> Do you plan to release an NPM package for ease of installation?

We don't plan on releasing an NPM package but the reporter is easily fetched and executed as a static binary:

```yaml
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
```

**Comment by dblandin** [comment]
Closing this issue as we've deprecated these language-specific test reporters.

**Pull request closed without merging**
