### PR TITLE
Re-merge pr #7

### PR DESCRIPTION
**Pull request by avdg**
I've just solved the merge conflict, added some semicolons and ran the test. There might be things I've overlooked.

Fixes #7

### CODE REVIEW

**Comment by etnbrd** [comment]
Thanks for solving the merge conflicts :)
We still need to wait for someone from the codeclimate repository to merge this :)

**Comment by Xiphe** [comment]
:+1:

**Comment by avdg** [comment]
@noahd1 Any thoughts about this PR?

**Comment by jpignata** [comment]
Closing due to staleness.

**Pull request closed without merging**
