### PR TITLE
Upgrade request package

### PR DESCRIPTION
**Pull request by aureooms**

### CODE REVIEW

**Comment by dblandin** [comment]
@aureooms Just curious: did you run into a problem with requests v2.74.0?

**Comment by aureooms** [comment]
It is using an old version of the uuid package which gives an annoying deprecation message on  install. No other complaints.

**Comment by SimenB** [comment]
@dblandin Could you do a release with this (might want to bump to 2.81.1 while you're at it)?
Request dropped support for node < 4 btw, so should be semver major

**Comment by SimenB** [comment]
Out in 0.5.0, woo!

**Pull request merged**
