### PR TITLE
Set minimum version of request to 2.40.0 (uses qs >1.0.0)

### PR DESCRIPTION
**Pull request by smockle**
Resolves https://app.snyk.io/vuln/npm:qs:20140806 and https://app.snyk.io/vuln/npm:qs:20140806-1

### CODE REVIEW

**Comment by hairyhenderson** [comment]
+1 - Can someone merge this?

**Comment by StephanBijzitter** [comment]
+1

**Comment by jpignata** [comment]
Thanks!

**Comment by StephanBijzitter** [comment]
Time for v1.0.1 I'd say ;-)

**Comment by hairyhenderson** [comment]
@jpignata - any idea if this is going to be released soon?

**Comment by hairyhenderson** [comment]
@noahd1 @GordonDiggs @jpignata - Sorry for nagging, but can we get a v0.1.2 in npmjs with this updated dependency?

**Comment by jpignata** [comment]
@hairyhenderson Not a nag – thanks for the reminder! We'll do this shortly after the holiday.

**Comment by hairyhenderson** [comment]
Awesome, thanks @jpignata :) Have a great holiday!

**Pull request merged**
